#spring:
#  datasource:
#    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}?useSSL=false&serverTimezone=UTC
#    username: ${PROD_DB_USERNAME}
#    password: ${PROD_DB_PASSWORD}
#    name: WASBackend